### ISSUE TITLE
Import sigma AWS rules

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/suzaku-rules#1]
@fukusuket Could I ask you to look into how to automate importing AWS sigma rules into this repository.
We can have a `suzaku` folder for suzaku rules and a `sigma` folder for sigma rules just like in hayabusa.
`config` directory will hold config files.

Right now, there are only cloudtrail logs in sigma so we can just sync those to `./sigma/aws/cloudtrail/`.

**Comment by fukusuket** [comment]
Yes, I would love to look into!💪
